[package]
name = "photo_sorter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.18.0"
rayon = "1.7"
regex = "1.10"
chrono = "0.4"
serde_json = "1.0"
